program: src/model/train_encoder_decoder.py
method: grid
name: loss_sweep
metric:
    name: train_loss
    goal: minimize
parameters:
    NUM_ENCODER_BLOCKS:
        values: [4, 6]
    NUM_ENCODER_ATTHEADS: 
        values: [4, 6]
    NUM_DECODER_BLOCKS: 
        values: [4, 6]
    NUM_DECODER_ATTHEADS:
        values: [4, 6]
    EMBEDDING_DIM:
        values: [48, 96, 144]
